import Main from '@/components/main';
import Navbar from '@/components/molecules/navbar'
import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const routes = useRouter();

  useEffect(()=>{
    try{
        const token = JSON.parse(localStorage.getItem('users') || "").token;
        if(!token){
            routes.push("/login")
        }
        routes.push("/profile")
    }
    catch(e){
        routes.push("/login")
    }
},[routes])
  return (
    <>
    <Head>
      <title>Chat App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar/>
    <Main/>
    </>
    
  )
}