import ProfileComponent from "@/components/organisms/profile";
import axios from "axios";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { BASE_URL } from "./api/base";
import Head from "next/head";

const Profile = () =>{
    const routes = useRouter();
    const [currentUser , setCurrentUser] = useState({name : "" , bio:""});
    useEffect(()=>{
        (
            async function(){
                const res = await axios.get(`${BASE_URL}/user`,{
                    headers:{
                        Authorization: `Bearer ${JSON.parse(localStorage.getItem('users') || "").token}`
                    }
                })
                setCurrentUser(res.data.user)
            }
        )()
    },[])
    useEffect(()=>{
        try{
            const token = JSON.parse(localStorage.getItem('users') || "").token;
            if(!token){
                routes.push("/login")
            }
        }
        catch(e){
            routes.push("/login")
        }
    },[routes])

    return(
        <>
        <Head>
            <title>Profile section</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProfileComponent 
        name={currentUser.name}
        bio={currentUser.bio}
        />
        </>
        
    )
}

export default Profile;