name: CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: oC2P_fiKn8yeDpIUWUyhueGNhdoiRv4sjJazx2y_ZF4
          build_directory: ./build/
          build_command: npm run build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
