name: CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          version: 16.20
      - name: install dependencies
        run: npm install
      - name: build project
        run: npm run build
        
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: oC2P_fiKn8yeDpIUWUyhueGNhdoiRv4sjJazx2y_ZF4
          build_directory: ./next/
